# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/sor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/sor.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10protos/sor.proto\"E\n\x0bSparseValue\x12\x11\n\trow_index\x18\x01 \x01(\x04\x12\x14\n\x0c\x63olumn_index\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\x01\"j\n\x0cSparseMatrix\x12\x13\n\x0bmatrix_name\x18\x01 \x01(\t\x12\x11\n\trow_count\x18\x02 \x01(\x04\x12\x14\n\x0c\x63olumn_count\x18\x03 \x01(\x04\x12\x1c\n\x06values\x18\x04 \x03(\x0b\x32\x0c.SparseValue\"=\n\x06Vector\x12\x13\n\x0bvector_name\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x04\x12\x0e\n\x06values\x18\x03 \x03(\x01\"\xb6\x02\n\x0eSorReturnValue\x12\x13\n\x0bresult_name\x18\x01 \x01(\t\x12\x36\n\x0estoppig_reason\x18\x03 \x01(\x0e\x32\x1e.SorReturnValue.StoppingReason\x12\x17\n\x06vector\x18\x04 \x01(\x0b\x32\x07.Vector\"\xbd\x01\n\x0eStoppingReason\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1a\n\x16X_SEQUENCE_CONVERGENCE\x10\x01\x12\x18\n\x14RESIDUAL_CONVERGENCE\x10\x02\x12\x1a\n\x16MAX_ITERATIONS_REACHED\x10\x03\x12\x19\n\x15X_SEQUENCE_DIVERGENCE\x10\x04\x12\x14\n\x10ZERO_ON_DIAGONAL\x10\x05\x12\x1b\n\x17UNRECOVERABLE_EXCEPTION\x10\x06\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SORRETURNVALUE_STOPPINGREASON = _descriptor.EnumDescriptor(
  name='StoppingReason',
  full_name='SorReturnValue.StoppingReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X_SEQUENCE_CONVERGENCE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESIDUAL_CONVERGENCE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_ITERATIONS_REACHED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X_SEQUENCE_DIVERGENCE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZERO_ON_DIAGONAL', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNRECOVERABLE_EXCEPTION', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=384,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_SORRETURNVALUE_STOPPINGREASON)


_SPARSEVALUE = _descriptor.Descriptor(
  name='SparseValue',
  full_name='SparseValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_index', full_name='SparseValue.row_index', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column_index', full_name='SparseValue.column_index', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SparseValue.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=89,
)


_SPARSEMATRIX = _descriptor.Descriptor(
  name='SparseMatrix',
  full_name='SparseMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix_name', full_name='SparseMatrix.matrix_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row_count', full_name='SparseMatrix.row_count', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column_count', full_name='SparseMatrix.column_count', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='SparseMatrix.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=197,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_name', full_name='Vector.vector_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='Vector.length', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='Vector.values', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=260,
)


_SORRETURNVALUE = _descriptor.Descriptor(
  name='SorReturnValue',
  full_name='SorReturnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_name', full_name='SorReturnValue.result_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stoppig_reason', full_name='SorReturnValue.stoppig_reason', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vector', full_name='SorReturnValue.vector', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SORRETURNVALUE_STOPPINGREASON,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=573,
)

_SPARSEMATRIX.fields_by_name['values'].message_type = _SPARSEVALUE
_SORRETURNVALUE.fields_by_name['stoppig_reason'].enum_type = _SORRETURNVALUE_STOPPINGREASON
_SORRETURNVALUE.fields_by_name['vector'].message_type = _VECTOR
_SORRETURNVALUE_STOPPINGREASON.containing_type = _SORRETURNVALUE
DESCRIPTOR.message_types_by_name['SparseValue'] = _SPARSEVALUE
DESCRIPTOR.message_types_by_name['SparseMatrix'] = _SPARSEMATRIX
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['SorReturnValue'] = _SORRETURNVALUE

SparseValue = _reflection.GeneratedProtocolMessageType('SparseValue', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEVALUE,
  __module__ = 'protos.sor_pb2'
  # @@protoc_insertion_point(class_scope:SparseValue)
  ))
_sym_db.RegisterMessage(SparseValue)

SparseMatrix = _reflection.GeneratedProtocolMessageType('SparseMatrix', (_message.Message,), dict(
  DESCRIPTOR = _SPARSEMATRIX,
  __module__ = 'protos.sor_pb2'
  # @@protoc_insertion_point(class_scope:SparseMatrix)
  ))
_sym_db.RegisterMessage(SparseMatrix)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'protos.sor_pb2'
  # @@protoc_insertion_point(class_scope:Vector)
  ))
_sym_db.RegisterMessage(Vector)

SorReturnValue = _reflection.GeneratedProtocolMessageType('SorReturnValue', (_message.Message,), dict(
  DESCRIPTOR = _SORRETURNVALUE,
  __module__ = 'protos.sor_pb2'
  # @@protoc_insertion_point(class_scope:SorReturnValue)
  ))
_sym_db.RegisterMessage(SorReturnValue)


# @@protoc_insertion_point(module_scope)
